spring:
  application:
    name: server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

management:
  health:
    redis:
      enabled: false

server:
  port: ${application-port} #注册中心端口
eureka:
  server:
    enable-self-preservation: false  # 设为false，关闭自我保护，会清理无效节点
    eviction-interval-timer-in-ms: 30000  # 清理无效节点间隔时间（单位毫秒，默认是60*1000）
  instance:
    hostname: ${application-host}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

hystrix:
  command:
    default: #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #断路器超时时间，默认1000ms

logging:
  config: classpath:config/log4j2-spring.xml


