Configuration:
  status: info
  Appenders:
    Console:
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p ${PID:-} [%15.15t] %-30.30C{1.} : %m%n"
    FileAppender:
      name: MYSQL
  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: CONSOLE
        - ref: MYSQL