spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: ${config-git-uri}
          username: ${config-git-username}
          password: ${config-git-password}
          default-label:  ${config-git-label}
          force-pull: true
          skip-ssl-validation: true
  rabbitmq:
    host: ${rabbitmq-host}
    port: ${rabbitmq-port}
    username: ${rabbitmq-username}
    password: ${rabbitmq-password}

server:
  port: ${application-port}

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://${server-host}:${server-port}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${application-host}:${application-port}
    ip-address: ${application-host}

feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true

hystrix:
  command:
    default: #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #断路器超时时间，默认1000ms

logging:
  config: classpath:config/log4j2-spring.xml
